### ISSUE TITLE
Data collected from standard collectd client are not written into rrd on collectd-pw server

### ISSUE THREAD

**Issue by samyscoub** [perfwatcher/collectd-pw#11]
Hello,

i've a standard collectd client ( version 5.1.0 ) who talked to collectd-pw server ( version 5.4.0 ).
Into my tcpdump i see some messages between the two hosts but nothing is written on server side concerning my collectd client.

Are these versions compatibles ?

Thanks.

**Comment by feraudet** [comment]
Hi,

These version are compatible. 
Is your datas are visible when you do a `collectdctl listval` ?

**Comment by samyscoub** [comment]
With this command i've this result : 

```
$# collectdctl listval
ERROR: Failed to connect to daemon at unix:/usr/var/run/collectd-unixsock: No such file or directory.
```

And in my tshark capture i've found this :

```
... 28 values for 6 plugins, 0 messages, 29 unknown
```

Can you help me please ?

**Comment by feraudet** [comment]
Unknown values look like as a types.db issue.

Have a look on `TypesDB` part of your configuration. Be sure files exists.

**Comment by samyscoub** [comment]
Here are my existing Types files :

```
TypesDB     "/usr/share/collectd/types.db" "/etc/types-perfwatcher.db"
```

And the fields into the tshark capture :

```
queue_length,entropy,load,users,swap_io,if_octets,if_packets,if_errors,if_octets,if_packets,if_errors,if_octets,if_packets,if_errors,memory,ps_state,fork_rate
cpu,if_octets,if_packets,total_values,queue_length,entropy,load,users,swap_io,if_octets,if_packets,if_errors,if_octets,if_packets,if_errors
if_octets,if_packets,if_errors,memory,ps_state,fork_rate,cpu,if_octets,if_packets,total_values
queue_length,entropy,load,users,if_octets,if_packets,if_errors,if_octets,if_packets,if_errors,if_octets,if_packets,if_errors,swap_io,memory,ps_state,fork_rate
cpu,if_octets,if_packets,total_values,queue_length,entropy,load,users,swap_io,if_octets,if_packets,if_errors,if_octets,if_packets,if_errors
if_octets,if_packets,if_errors,memory,ps_state,fork_rate,cpu,if_octets,if_packets,total_values
queue_length,entropy,load,users,swap_io,if_octets,if_packets,if_errors,if_octets,if_packets,if_errors,if_octets,if_packets,if_errors,memory,ps_state,fork_rate
cpu,if_octets,if_packets,total_values,queue_length,entropy,load,swap_io,users,swap_io,if_octets,if_packets,if_errors,if_octets,if_packets
if_errors,if_octets,if_packets,memory,if_errors,ps_state,fork_rate,cpu,if_octets,if_packets,total_values
total_values,queue_length,entropy,load,users,swap_io,if_octets,if_packets,if_errors,if_octets,if_packets,if_errors,if_octets,if_packets,if_errors,memory,ps_state
ps_state,fork_rate,cpu,if_octets,if_packets,total_values,queue_length,entropy,load,swap_io,if_octets,if_packets,if_errors,if_octets
if_packets,if_errors,if_octets,if_packets,if_errors,memory,users,ps_state,fork_rate,cpu,if_octets,if_packets
total_values,queue_length,entropy,load,users,if_octets,if_packets,if_errors,if_octets,if_packets,if_errors,if_octets,if_packets,if_errors,swap_io,memory,ps_state
ps_state,fork_rate,cpu,if_octets,if_packets,total_values,queue_length,entropy,load,swap_io,if_octets,if_packets
```

**Comment by feraudet** [comment]
tshark output say to us that data come to the server. To be sure that datas are handled by collectd-pw, please install unixsock plugin (http://collectd.org/documentation/manpages/collectd-unixsock.5.shtml) then run `collectdctl listval`

**Comment by ymettier** [comment]
No more feedback. If you feel that we should reopen this issue, please comment here and ask for it with more information so we can try to help.

**Comment by 4l1fe** [comment]
> tshark output say to us that data come to the server. To be sure that datas are handled by collectd-pw, please install unixsock plugin (http://collectd.org/documentation/manpages/collectd-unixsock.5.shtml) then run `collectdctl listval`

I got this [error](https://github.com/perfwatcher/collectd-pw/issues/11#issuecomment-42171277)  and you solution fixed it up. But i didn't install the plugin, i uncomment it in the collectd config file.
