### ISSUE TITLE
Question about mongodb-Write plugin

### ISSUE THREAD

**Issue by sseshachala** [perfwatcher/collectd-pw#2]
The mongodb node within plugin should include username, password and db name for security purposes.
This way - the plugin can write to diferent nodes in a cluster.
Right now - it seems you can only write to local mongodb. The plugin config with auth credentials is copied below for reference. Please correct me if am wrong and clarify if this is a feature request being cooked into future release.

<Plugin write_mongodb>
        <Node "node1">
                Host "localhost"
                Port "27017"
                Timeout 1000
                StoreRates false
  username "john" password "doee" databse "somedb"
        </Node>
</Plugin>

**Comment by ymettier** [comment]
Hello,

mongoDB has no specific support in perfwatcher/collectd-pw.
You should open an issue at the original collectd place (https://github.com/collectd/collectd)

Regards,
Yves
