### ISSUE TITLE
Example config for basic agregator

### ISSUE THREAD

**Issue by sseshachala** [perfwatcher/collectd-pw#3]
LoadPlugin basic_aggregator
<Plugin basic_aggregator>
    Aggregators_config_file "/<path to perfwatcher>/etc/aggregator.conf"
</Plugin>
Is there any example config available?

**Comment by ymettier** [comment]
Hello,

Yes (no need to start with so many slashes) : 

```
[extract from collectd.conf]
LoadPlugin basic_aggregator
<Plugin basic_aggregator>
    Aggregators_config_file "/etc/collectd/aggregator.conf"
</Plugin>
```

In the file /etc/collectd/aggregator.conf, write something like this : 

```
<aggregator>
  resultvalue "my_aggregator_1/load/load"
  operation "AVG"
  operation "SUM"
  <valuelist manual>
    type "host1/load/load"
    type "host2/load/load"
    type "host3/load/load"
  </valuelist>
</aggregator>
```

This will aggregate (sum and average) the load/load for the 3 hosts host1, host2, host3.
The result will be a new metric "my_aggregator_1/load/load"

```
<aggregator>
  resultvalue "my_aggregator_2/cpu-total/cpu
  operation "AVG"
  operation "SUM"
  <valuelist manual>
    type "host1/cpu-total/cpu"
    type "host2/cpu-total/cpu"
  </valuelist>
</aggregator>
```

This will aggregate all typeinstances of cpu-total/cpu for host1 and host2.

If you follow the installation procedure of perfwatcher, there is a tool that you will install in crontab and that will create automatically aggregators for you.

Regards,
Yves
