### ISSUE TITLE
Dependency error on ubuntu

### ISSUE THREAD

**Issue by sseshachala** [perfwatcher/collectd-pw#4]
Json.h and jsonrpc  not foumd..
I tried multiple libraries like libjson, https://github.com/cinemast/libjson-rpc-cpp/tree/master/build.
Can you please let me know which library i need to use.
I am using Release 5.2.1 on ubuntu.

 Libraries:
    libcurl . . . . . . . yes
    libdbi  . . . . . . . yes
    libcredis . . . . . . no (credis.h not found)
    libesmtp  . . . . . . yes
    libganglia  . . . . . yes
    libgcrypt . . . . . . yes
    libiokit  . . . . . . no
    libiptc . . . . . . . yes
    libjson . . . . . . . no (json.h not found)
    libjvm  . . . . . . . no (jar not found)
    libkstat  . . . . . . no (Solaris only)
    libkvm  . . . . . . . no
    libmemcached  . . . . yes
    libmicrohttpd . . . . yes
    libmodbus . . . . . . no (pkg-config doesn't know libmodbus)
    libmysql  . . . . . . yes
    libnetapp . . . . . . no (netapp_api.h not found)
    libnetlink  . . . . . no (libnetlink.h not found)
    libnetsnmp  . . . . . yes
    libnotify . . . . . . yes
    liboconfig  . . . . . yes (shipped version)
    libopenipmi . . . . . no (/usr/bin/pkg-config --cflags OpenIPMIpthread failed)
    liboping  . . . . . . yes
    libpcap . . . . . . . yes
    libperfstat . . . . . no (AIX only)
    libperl . . . . . . . no
    libpq . . . . . . . . yes
    libpthread  . . . . . yes
    librabbitmq . . . . . no (amqp.h not found)
    librouteros . . . . . no (routeros_api.h not found)
    librrd  . . . . . . . yes
    libsensors  . . . . . yes
    libstatgrab . . . . . no (pkg-config doesn't know libstatgrab)
    libtokyotyrant  . . . yes
    libupsclient  . . . . yes
    libvarnish  . . . . . no (pkg-config doesn't know varnishapi)
    libvirt . . . . . . . yes
    libxml2 . . . . . . . yes
    libxmms . . . . . . . no
    libyajl . . . . . . . yes
    libz      . . . . . . yes
    libevent  . . . . . . 
    protobuf-c  . . . . . yes
    oracle  . . . . . . . no (ORACLE_HOME is not set)
    python  . . . . . . . yes

  Features:
    daemon mode . . . . . yes
    debug . . . . . . . . no

  Bindings:
    perl  . . . . . . . . yes

  Modules:
    aggregation . . . . . yes
    amqp    . . . . . . . no
    apache  . . . . . . . yes
    apcups  . . . . . . . yes
    apple_sensors . . . . no
    ascent  . . . . . . . yes
    basic_aggragator  . . yes
    battery . . . . . . . yes
    bind  . . . . . . . . yes
    conntrack . . . . . . yes
    contextswitch . . . . yes
    cpu . . . . . . . . . yes
    cpufreq . . . . . . . yes
    csv . . . . . . . . . yes
    curl  . . . . . . . . yes
    curl_json . . . . . . yes
    curl_xml  . . . . . . yes
    dbi . . . . . . . . . yes
    df  . . . . . . . . . yes
    disk  . . . . . . . . yes
    dns . . . . . . . . . yes
    email . . . . . . . . yes
    entropy . . . . . . . yes
    ethstat . . . . . . . yes
    exec  . . . . . . . . yes
    filecount . . . . . . yes
    fscache . . . . . . . yes
    gmond . . . . . . . . yes
    hddtemp . . . . . . . yes
    interface . . . . . . yes
    ipmi  . . . . . . . . no
    iptables  . . . . . . yes
    ipvs  . . . . . . . . yes
    irq . . . . . . . . . yes
    java  . . . . . . . . no
    jsonrpc . . . . . . . no (dependency error)
    jsonrpc_base  . . . . yes
    jsonrpc_perfwatcher . yes
    jsonrpc_topps . . . . yes
    libvirt . . . . . . . yes
    load  . . . . . . . . yes
    logfile . . . . . . . yes
    lpar... . . . . . . . no
    madwifi . . . . . . . yes
    match_empty_counter . yes
    match_hashed  . . . . yes
    match_regex . . . . . yes
    match_timediff  . . . yes
    match_value . . . . . yes
    mbmon . . . . . . . . yes
    md  . . . . . . . . . yes
    memcachec . . . . . . yes
    memcached . . . . . . yes
    memory  . . . . . . . yes
    modbus  . . . . . . . no
    multimeter  . . . . . yes
    mysql . . . . . . . . yes
    netapp  . . . . . . . no
    netlink . . . . . . . no
    network . . . . . . . yes
    nfs . . . . . . . . . yes
    nginx . . . . . . . . yes
    notify_desktop  . . . yes
    notify_email  . . . . yes
    notify_file . . . . . yes
    ntpd  . . . . . . . . yes
    numa  . . . . . . . . yes
    nut . . . . . . . . . yes
    olsrd . . . . . . . . yes
    onewire . . . . . . . no
    openvpn . . . . . . . yes
    oracle  . . . . . . . no
    perl  . . . . . . . . no (needs libperl)
    pf  . . . . . . . . . no
    pinba . . . . . . . . yes
    ping  . . . . . . . . yes
    postgresql  . . . . . yes
    powerdns  . . . . . . yes
    processes . . . . . . yes
    protocols . . . . . . yes
    python  . . . . . . . yes
    redis . . . . . . . . no
    routeros  . . . . . . no
    rrdcached . . . . . . yes
    rrdtool . . . . . . . yes
    rrdtool_createonly  . yes
    sensors . . . . . . . yes
    serial  . . . . . . . yes
    snmp  . . . . . . . . yes
    swap  . . . . . . . . yes
    sysconfig . . . . . . yes
    syslog  . . . . . . . yes
    table . . . . . . . . yes
    tail  . . . . . . . . yes
    tape  . . . . . . . . no
    target_notification . yes
    target_replace  . . . yes
    target_scale  . . . . yes
    target_set  . . . . . yes
    target_v5upgrade  . . yes
    tcpconns  . . . . . . yes
    teamspeak2  . . . . . yes
    ted . . . . . . . . . yes
    thermal . . . . . . . yes
    threshold . . . . . . yes
    top . . . . . . . . . yes
    tokyotyrant . . . . . yes
    unixsock  . . . . . . yes
    uptime  . . . . . . . yes
    users . . . . . . . . yes
    uuid  . . . . . . . . yes
    varnish . . . . . . . no
    vmem  . . . . . . . . yes
    vserver . . . . . . . yes
    wireless  . . . . . . yes
    write_graphite  . . . yes
    write_http  . . . . . yes
    write_redis . . . . . no
    write_mongodb . . . . yes
    write_top . . . . . . yes
    xmms  . . . . . . . . no
    zfs_arc . . . . . . . no

**Comment by ymettier** [comment]
Hello,

https://github.com/json-c/json-c

This is the one you need.

Regards,
Yves

**Comment by chicofranchico** [comment]
Hi, I'm having the same problem when running configure. How do I tell it to point to the json-c lib? Thanks a lot!

**Comment by ymettier** [comment]
```
./configure --help
[...]
collectd additional packages:
  --with-libjson[=PREFIX] Path to libjson.
[...]
```

If you install 0.10, check the `Compile json-c` section in http://perfwatcher.org/installation_server.html and be sure that you installed everything.

Notes : 
- 0.9 contains a bug and you will not be able to use Perfwatcher.
- 0.11 may work but we have not tested it yet. 0.11 fixes the problem described in `Compile json-c` section of http://perfwatcher.org/installation_server.html

**Comment by chicofranchico** [comment]
Wicked! Everything works now! Thank you.
