### ISSUE TITLE
Error while compiling code - jsonrpc_cb_topps.c - can you please help?

### ISSUE THREAD

**Issue by sseshachala** [perfwatcher/collectd-pw#5]
libtool: link: gcc -shared  -fPIC -DPIC  .libs/rrdtool_createonly_la-rrdtool_createonly.o .libs/rrdtool_createonly_la-utils_rrdcreate.o   -lrrd_th -lm -ldl  -O2   -Wl,-soname -Wl,rrdtool_createonly.so -o .libs/rrdtool_createonly.so
libtool: link: ar cru .libs/rrdtool_createonly.a  rrdtool_createonly_la-rrdtool_createonly.o rrdtool_createonly_la-utils_rrdcreate.o
libtool: link: ranlib .libs/rrdtool_createonly.a
libtool: link: ( cd ".libs" && rm -f "rrdtool_createonly.la" && ln -s "../rrdtool_createonly.la" "rrdtool_createonly.la" )
jsonrpc_cb_topps.c: In function 'jsonrpc_cb_topps_get_top':
jsonrpc_cb_topps.c:203:40: error: 'last_before_flush_n' may be used uninitialized in this function [-Werror=uninitialized]
jsonrpc_cb_topps.c:146:13: note: 'last_before_flush_n' was declared here
jsonrpc_cb_topps.c:199:28: error: 'last_before_flush_tm' may be used uninitialized in this function [-Werror=uninitialized]
jsonrpc_cb_topps.c:147:13: note: 'last_before_flush_tm' was declared here
cc1: all warnings being treated as errors
make[3]: **\* [jsonrpc_la-jsonrpc_cb_topps.lo] Error 1
make[3]: Leaving directory `/root/downloads/monitoring/collectd-pw-release-5.2.1/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory`/root/downloads/monitoring/collectd-pw-release-5.2.1/src'
make[1]: **\* [all] Error 2
make[1]: Leaving directory `/root/downloads/monitoring/collectd-pw-release-5.2.1/src'
make: **\* [all-recursive] Error 1

**Comment by ymettier** [comment]
Hello,

Are you compiling the last version ? I do not see 'last_before_flush_n' line 203.
Please provide some more version information (5.2.1 does not seem to be enough).

However, you may have the same problem with the last version.
At lines 146 and 147, you can initialize to -1 (or any value). I added 2 assert() in my fix, but you can ignore them if you edit jsonrpc_cb_topps.c yourself.

Branchs plugin/jsonrpc and plugin-jsonrpc/5.2.0 are updated.
Branchs release/5.2.1 and release/5.2.0 will follow.

Does this fix your problem ?

Regards,
Yves

**Comment by sseshachala** [comment]
Finally - it seems to compile now.
